# Meta-Workflow: Complete Entire Proxy Agent Platform Project
# This is the master workflow that can systematically complete the entire project

workflow_id: "meta_complete_project"
name: "Complete Entire Proxy Agent Platform Project"
description: "Meta-workflow that orchestrates the systematic completion of all 6 epics through hierarchical AI agent collaboration. Can be pointed to by any AI agent to complete the entire project from current state to production-ready platform."
version: "1.0.0"

# Classification
workflow_type: "meta"
epic_id: null
phase_id: null

# Execution configuration
strategy: "sequential"
max_parallel_steps: 3
timeout_hours: 168  # 1 week for complete project

# Dependencies and triggers
dependencies: []
triggers: ["complete_project", "project_kickoff", "epic_completion_sequence"]

# Agent configuration
required_agents:
  - "project_manager"
  - "architect"
  - "implementation"
  - "quality"
  - "integration"

agent_config:
  project_manager:
    orchestration_level: "meta"
    epic_coordination: true
    human_checkpoint_management: true
  architect:
    system_level_design: true
    cross_epic_integration: true
  implementation:
    tdd_enforcement: "strict"
    pattern_consistency: true
  quality:
    comprehensive_validation: true
    cross_epic_testing: true
  integration:
    system_level_validation: true
    production_readiness: true

# Workflow steps
steps:
  - step_id: "M1_project_analysis"
    name: "Comprehensive Project Analysis"
    description: "Analyze current project state, identify completed work, and create master execution plan for all 6 epics"
    agent_role: "project_manager"
    action_type: "plan"
    action_details:
      analysis_scope: "entire_project"
      epic_assessment: true
      dependency_mapping: true
      current_state_evaluation: true
      master_plan_creation: true
    dependencies: []
    parallel_group: null
    timeout_minutes: 60
    validation_gates:
      - name: "project_analysis_completeness"
        description: "Ensure comprehensive project analysis covers all aspects"
        agent_role: "architect"
        validation_command: "validate_project_analysis"
        success_criteria:
          all_epics_analyzed: true
          dependencies_mapped: true
          current_state_assessed: true
          execution_plan_created: true
        failure_action: "block"
        retry_count: 2
    tdd_required: false
    input_context:
      master_task_list: "docs/MASTER_TASK_LIST.md"
      epic_breakdown: "tasks/epics/"
      current_codebase: "entire_repository"
      code_review_report: "CODE_REVIEW_REPORT.md"
    expected_outputs:
      - "project_state_analysis"
      - "epic_execution_plan"
      - "dependency_matrix"
      - "timeline_estimates"
    success_criteria:
      project_analyzed: true
      execution_plan_ready: true
      dependencies_resolved: true

  - step_id: "M2_critical_issues_resolution"
    name: "Resolve Critical Issues First"
    description: "Execute critical issue workflows to resolve production-blocking problems before epic implementation"
    agent_role: "project_manager"
    action_type: "orchestrate"
    action_details:
      orchestration_type: "critical_workflows"
      workflows_to_execute:
        - "workflows/critical/security-audit.yml"
        - "workflows/critical/architecture-cleanup.yml"
        - "workflows/critical/router-implementation.yml"
      execution_strategy: "sequential"
      failure_handling: "abort_on_critical_failure"
    dependencies:
      - task_id: "M1_project_analysis"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 240  # 4 hours for all critical issues
    validation_gates:
      - name: "critical_issues_resolved"
        description: "All critical issues must be resolved before proceeding"
        agent_role: "quality"
        validation_command: "validate_critical_issues_resolved"
        success_criteria:
          security_vulnerabilities_fixed: true
          architecture_issues_resolved: true
          missing_components_implemented: true
        failure_action: "block"
        retry_count: 1
    tdd_required: false
    input_context:
      critical_workflows: "workflows/critical/"
      code_review_issues: "high_priority_blocking"
      security_requirements: "production_ready"
    expected_outputs:
      - "critical_issues_resolution_report"
      - "security_audit_results"
      - "architecture_improvements"
    success_criteria:
      all_critical_issues_resolved: true
      security_audit_passed: true
      architecture_stable: true

  - step_id: "M3_epic_1_core_agents"
    name: "Execute Epic 1: Core Proxy Agents"
    description: "Complete Epic 1 with all 23 tasks across 6 phases including human validation checkpoints"
    agent_role: "project_manager"
    action_type: "orchestrate"
    action_details:
      orchestration_type: "epic_execution"
      target_epic: "epic-1-core-proxy-agents"
      workflow_path: "workflows/epic/epic-1-core-agents.yml"
      human_checkpoints_enabled: true
      phases: 6
      total_tasks: 23
    dependencies:
      - task_id: "M2_critical_issues_resolution"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 2400  # 40 hours for Epic 1
    validation_gates:
      - name: "epic_1_completion_validation"
        description: "Epic 1 must be fully completed with human validation"
        agent_role: "integration"
        validation_command: "validate_epic_1_completion"
        success_criteria:
          all_phases_completed: true
          all_tasks_completed: true
          human_validation_passed: true
          core_agents_functional: true
        failure_action: "block"
        retry_count: 1
    tdd_required: true
    input_context:
      epic_definition: "tasks/epics/epic-1-core-proxy-agents/tasks.md"
      agent_specifications: "proxy_agent_platform/agents/"
      test_requirements: "95%_coverage_minimum"
    expected_outputs:
      - "epic_1_completion_report"
      - "core_agent_implementations"
      - "comprehensive_test_suite"
      - "human_validation_results"
    success_criteria:
      epic_1_completed: true
      all_agents_implemented: true
      tests_passing: true
      human_validation_approved: true

  - step_id: "M4_epic_2_gamification"
    name: "Execute Epic 2: Gamification System"
    description: "Implement comprehensive gamification system with XP, achievements, and progress tracking"
    agent_role: "project_manager"
    action_type: "orchestrate"
    action_details:
      orchestration_type: "epic_execution"
      target_epic: "epic-2-gamification-system"
      workflow_path: "workflows/epic/epic-2-gamification.yml"
      depends_on_epic_1: true
      integration_with_core_agents: true
    dependencies:
      - task_id: "M3_epic_1_core_agents"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 1440  # 24 hours for Epic 2
    validation_gates:
      - name: "gamification_system_validation"
        description: "Gamification system must integrate with core agents"
        agent_role: "integration"
        validation_command: "validate_gamification_integration"
        success_criteria:
          xp_system_functional: true
          achievements_implemented: true
          progress_tracking_working: true
          agent_integration_complete: true
        failure_action: "block"
        retry_count: 2
    tdd_required: true
    input_context:
      epic_definition: "tasks/epics/epic-2-gamification-system/tasks.md"
      core_agents_context: "epic_1_outputs"
      database_schema: "existing_models"
    expected_outputs:
      - "gamification_system"
      - "xp_calculation_engine"
      - "achievement_framework"
      - "progress_tracking_system"
    success_criteria:
      gamification_completed: true
      agent_integration_working: true
      user_engagement_metrics: true

  - step_id: "M5_parallel_epics_3_4"
    name: "Execute Epics 3-4 in Parallel"
    description: "Execute Epic 3 (Mobile Integration) and Epic 4 (Real-time Dashboard) in parallel as they have minimal dependencies"
    agent_role: "project_manager"
    action_type: "orchestrate"
    action_details:
      orchestration_type: "parallel_epic_execution"
      target_epics:
        - "epic-3-mobile-integration"
        - "epic-4-realtime-dashboard"
      workflow_paths:
        - "workflows/epic/epic-3-mobile.yml"
        - "workflows/epic/epic-4-dashboard.yml"
      parallel_execution: true
      resource_allocation: "balanced"
    dependencies:
      - task_id: "M4_epic_2_gamification"
        dependency_type: "requires"
    parallel_group: "epics_3_4"
    timeout_minutes: 1800  # 30 hours for both epics in parallel
    validation_gates:
      - name: "parallel_epics_validation"
        description: "Both Epic 3 and Epic 4 must complete successfully"
        agent_role: "integration"
        validation_command: "validate_parallel_epics_completion"
        success_criteria:
          epic_3_completed: true
          epic_4_completed: true
          mobile_integration_working: true
          dashboard_functional: true
          cross_epic_integration: true
        failure_action: "block"
        retry_count: 1
    tdd_required: true
    input_context:
      epic_3_definition: "tasks/epics/epic-3-mobile-integration/tasks.md"
      epic_4_definition: "tasks/epics/epic-4-realtime-dashboard/tasks.md"
      previous_epic_outputs: "epics_1_2_context"
    expected_outputs:
      - "mobile_integration_system"
      - "realtime_dashboard"
      - "cross_platform_compatibility"
      - "performance_metrics"
    success_criteria:
      both_epics_completed: true
      mobile_dashboard_integrated: true
      performance_acceptable: true

  - step_id: "M6_epic_5_learning_optimization"
    name: "Execute Epic 5: Learning & Optimization"
    description: "Implement AI learning capabilities and system optimization features"
    agent_role: "project_manager"
    action_type: "orchestrate"
    action_details:
      orchestration_type: "epic_execution"
      target_epic: "epic-5-learning-optimization"
      workflow_path: "workflows/epic/epic-5-learning.yml"
      requires_all_previous_epics: true
      optimization_focus: true
    dependencies:
      - task_id: "M5_parallel_epics_3_4"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 1440  # 24 hours for Epic 5
    validation_gates:
      - name: "learning_system_validation"
        description: "Learning and optimization systems must enhance existing functionality"
        agent_role: "quality"
        validation_command: "validate_learning_optimization"
        success_criteria:
          learning_algorithms_functional: true
          optimization_improvements_measurable: true
          system_performance_enhanced: true
          user_experience_improved: true
        failure_action: "block"
        retry_count: 2
    tdd_required: true
    input_context:
      epic_definition: "tasks/epics/epic-5-learning-optimization/tasks.md"
      all_previous_epic_outputs: "complete_system_context"
      performance_baselines: "current_metrics"
    expected_outputs:
      - "learning_optimization_system"
      - "performance_improvements"
      - "user_behavior_analytics"
      - "adaptive_algorithms"
    success_criteria:
      learning_system_operational: true
      measurable_improvements: true
      optimization_effective: true

  - step_id: "M7_epic_6_testing_quality"
    name: "Execute Epic 6: Comprehensive Testing & Quality"
    description: "Implement comprehensive testing suite and quality assurance for the entire platform"
    agent_role: "quality"
    action_type: "orchestrate"
    action_details:
      orchestration_type: "epic_execution"
      target_epic: "epic-6-testing-quality"
      workflow_path: "workflows/epic/epic-6-quality.yml"
      comprehensive_testing: true
      system_wide_validation: true
    dependencies:
      - task_id: "M6_epic_5_learning_optimization"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 960  # 16 hours for Epic 6
    validation_gates:
      - name: "comprehensive_quality_validation"
        description: "Entire system must pass comprehensive quality validation"
        agent_role: "integration"
        validation_command: "validate_comprehensive_system_quality"
        success_criteria:
          test_coverage_above_95: true
          all_integration_tests_passing: true
          performance_benchmarks_met: true
          security_audit_clean: true
          production_readiness_confirmed: true
        failure_action: "block"
        retry_count: 1
    tdd_required: true
    input_context:
      epic_definition: "tasks/epics/epic-6-testing-quality/tasks.md"
      complete_system: "all_epic_outputs"
      quality_standards: "production_grade"
    expected_outputs:
      - "comprehensive_test_suite"
      - "quality_assurance_report"
      - "performance_benchmarks"
      - "production_readiness_certification"
    success_criteria:
      comprehensive_testing_complete: true
      quality_standards_met: true
      production_ready: true

  - step_id: "M8_final_integration_validation"
    name: "Final System Integration & Production Validation"
    description: "Final comprehensive system validation and production readiness confirmation"
    agent_role: "integration"
    action_type: "integrate"
    action_details:
      integration_type: "complete_system_validation"
      validation_scope: "entire_platform"
      production_simulation: true
      end_to_end_testing: true
      performance_validation: true
      security_final_check: true
    dependencies:
      - task_id: "M7_epic_6_testing_quality"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 180  # 3 hours for final validation
    validation_gates:
      - name: "production_readiness_final_check"
        description: "Final validation that system is production-ready"
        agent_role: "integration"
        validation_command: "final_production_readiness_check"
        success_criteria:
          all_epics_integrated: true
          end_to_end_workflows_functional: true
          performance_benchmarks_exceeded: true
          security_requirements_met: true
          deployment_ready: true
        failure_action: "block"
        retry_count: 1
    tdd_required: false
    input_context:
      complete_system: "all_6_epics"
      production_requirements: "full_specification"
      performance_targets: "defined_benchmarks"
    expected_outputs:
      - "final_integration_report"
      - "production_readiness_certification"
      - "deployment_instructions"
      - "system_documentation"
    success_criteria:
      system_fully_integrated: true
      production_ready: true
      deployment_documentation_complete: true
    git_integration:
      create_commit: true
      commit_type: "feat"
      commit_message: "🎉 Complete Proxy Agent Platform Project\n\nAll 6 epics successfully implemented and integrated\n✅ Epic 1: Core Proxy Agents (Task, Focus, Energy, Progress)\n✅ Epic 2: Gamification System (XP, Achievements, Streaks)\n✅ Epic 3: Mobile Integration\n✅ Epic 4: Real-time Dashboard\n✅ Epic 5: Learning & Optimization\n✅ Epic 6: Comprehensive Testing & Quality\n\n🚀 Production-ready platform achieved\n📊 95%+ test coverage\n🔒 Security audited and hardened\n📱 Cross-platform compatibility\n🧠 AI learning algorithms operational\n\nThis completes the entire Proxy Agent Platform project roadmap."
      files_to_commit:
        - "docs/project/PROJECT_COMPLETION_REPORT.md"
        - "docs/deployment/PRODUCTION_DEPLOYMENT_GUIDE.md"
        - "CHANGELOG.md"
        - "README.md"
      create_tag: true
      tag_name: "v1.0.0"
      tag_message: "🎉 Proxy Agent Platform v1.0.0 - Production Release\n\nComplete implementation of all 6 epics through hierarchical AI agent collaboration.\nProduction-ready platform with comprehensive testing, security hardening, and cross-platform compatibility."
      push_to_remote: true
      create_release: true
      release_notes: "Complete implementation of the Proxy Agent Platform through systematic AI agent collaboration. All 6 epics delivered with TDD methodology, comprehensive testing, and production-ready quality."

# Global validation gates
global_validation_gates:
  - name: "complete_project_validation"
    description: "Comprehensive validation that entire project is complete and production-ready"
    agent_role: "project_manager"
    validation_command: "validate_complete_project"
    success_criteria:
      all_6_epics_completed: true
      all_critical_issues_resolved: true
      comprehensive_testing_passed: true
      production_deployment_ready: true
      human_validations_approved: true
    failure_action: "block"
    retry_count: 1

# Success criteria
success_criteria:
  project_analysis_complete: true
  critical_issues_resolved: true
  epic_1_core_agents_complete: true
  epic_2_gamification_complete: true
  epic_3_mobile_integration_complete: true
  epic_4_dashboard_complete: true
  epic_5_learning_optimization_complete: true
  epic_6_testing_quality_complete: true
  final_integration_validated: true
  production_ready: true

# Human interaction
human_checkpoints:
  - "M3_epic_1_core_agents"  # Human validation for core agents
  - "M8_final_integration_validation"  # Final human approval
approval_required: false

# Metadata and tracking
created_by: "workflow_system"
tags:
  - "meta"
  - "complete_project"
  - "all_epics"
  - "hierarchical_orchestration"
  - "production_ready"