# Critical Security Audit Workflow
# Fixes security vulnerabilities identified in code review

workflow_id: "critical_security_audit"
name: "Critical Security Audit and Vulnerability Remediation"
description: "Systematic security audit and remediation of critical vulnerabilities including CORS configuration, error handling, and general security hardening"
version: "1.0.0"

# Classification
workflow_type: "critical"
epic_id: null
phase_id: null

# Execution configuration
strategy: "sequential"
max_parallel_steps: 2
timeout_hours: 4

# Dependencies and triggers
dependencies: []
triggers: ["security_vulnerability_detected", "manual_security_audit"]

# Agent configuration
required_agents:
  - "architect"
  - "implementation"
  - "quality"
  - "integration"

agent_config:
  architect:
    focus: "security_architecture"
    analysis_depth: "comprehensive"
  implementation:
    tdd_required: true
    security_focused: true
  quality:
    security_gates_enabled: true
    minimum_coverage: 95
  integration:
    security_testing: true

# Workflow steps
steps:
  - step_id: "S1_security_analysis"
    name: "Comprehensive Security Analysis"
    description: "Analyze entire codebase for security vulnerabilities with focus on CORS, authentication, and data exposure"
    agent_role: "architect"
    action_type: "plan"
    action_details:
      analysis_type: "security_audit"
      focus_areas:
        - "cors_configuration"
        - "error_handling"
        - "authentication_security"
        - "data_validation"
        - "secrets_management"
      critical_priority: true
    dependencies: []
    parallel_group: null
    timeout_minutes: 30
    validation_gates:
      - name: "security_analysis_completeness"
        description: "Ensure all critical security areas are analyzed"
        agent_role: "quality"
        validation_command: "validate_security_analysis_scope"
        success_criteria:
          areas_covered: 5
          critical_issues_identified: true
        failure_action: "block"
        retry_count: 2
    tdd_required: false
    input_context:
      codebase_paths:
        - "agent/main.py"
        - "proxy_agent_platform/"
        - "tests/"
      known_vulnerabilities:
        - "CORS allow_origins=['*'] in agent/main.py"
        - "Global exception handler exposes internal errors"
    expected_outputs:
      - "security_analysis_report"
      - "vulnerability_priority_matrix"
      - "remediation_plan"
    success_criteria:
      vulnerabilities_identified: true
      remediation_plan_created: true
      priority_classification: "complete"
    git_integration:
      create_commit: true
      commit_type: "docs"
      commit_message: "security: add comprehensive security analysis report"
      files_to_commit:
        - "docs/security/security_analysis_report.md"
        - "docs/security/vulnerability_matrix.md"

  - step_id: "S2_cors_vulnerability_fix"
    name: "Fix CORS Security Vulnerability"
    description: "Replace wildcard CORS configuration with secure, environment-specific origins"
    agent_role: "implementation"
    action_type: "implement"
    action_details:
      implementation_type: "security_fix"
      target_file: "agent/main.py"
      vulnerability_type: "cors_misconfiguration"
      security_requirements:
        - "Remove allow_origins=['*']"
        - "Implement environment-based CORS origins"
        - "Add CORS preflight handling"
        - "Validate origin against whitelist"
    dependencies:
      - task_id: "S1_security_analysis"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 45
    validation_gates:
      - name: "cors_security_validation"
        description: "Validate CORS configuration is secure"
        agent_role: "quality"
        validation_command: "validate_cors_security"
        success_criteria:
          wildcard_origins_removed: true
          environment_config_used: true
          security_test_passed: true
        failure_action: "block"
        retry_count: 3
    tdd_required: true
    input_context:
      current_cors_config: "allow_origins=['*']"
      security_requirements: "production_ready"
      environment_variables: ["ALLOWED_ORIGINS", "CORS_DEBUG"]
    expected_outputs:
      - "secure_cors_configuration"
      - "environment_variable_schema"
      - "cors_security_tests"
    success_criteria:
      cors_vulnerability_fixed: true
      tests_passing: true
      security_validation_passed: true
    git_integration:
      create_commit: true
      commit_type: "fix"
      commit_message: "security: fix critical CORS vulnerability\n\nReplace wildcard CORS origins with environment-based configuration\n- Remove allow_origins=['*'] security risk\n- Add environment variable for allowed origins\n- Include comprehensive CORS security tests"
      files_to_commit:
        - "agent/main.py"
        - "tests/security/test_cors_security.py"
        - ".env.example"

  - step_id: "S3_error_handling_hardening"
    name: "Harden Error Handling"
    description: "Secure global exception handler to prevent information disclosure"
    agent_role: "implementation"
    action_type: "implement"
    action_details:
      implementation_type: "security_hardening"
      target_file: "agent/main.py"
      security_focus: "error_handling"
      requirements:
        - "Remove internal error details from responses"
        - "Implement structured error logging"
        - "Add error classification system"
        - "Sanitize error messages for production"
    dependencies:
      - task_id: "S1_security_analysis"
        dependency_type: "requires"
    parallel_group: "security_fixes"
    timeout_minutes: 40
    validation_gates:
      - name: "error_handling_security"
        description: "Validate error handling doesn't leak sensitive information"
        agent_role: "quality"
        validation_command: "validate_error_security"
        success_criteria:
          internal_errors_hidden: true
          structured_logging: true
          production_safe: true
        failure_action: "block"
        retry_count: 2
    tdd_required: true
    input_context:
      current_error_handler: "global_exception_handler"
      debug_mode: false
      logging_requirements: "structured"
    expected_outputs:
      - "secure_error_handler"
      - "error_classification_system"
      - "security_logging_config"
    success_criteria:
      error_leakage_prevented: true
      logging_implemented: true
      security_tests_passed: true
    git_integration:
      create_commit: true
      commit_type: "security"
      commit_message: "security: harden error handling to prevent information disclosure\n\nImplement secure error handling patterns\n- Hide internal error details from API responses\n- Add structured security logging\n- Implement error classification system"
      files_to_commit:
        - "agent/main.py"
        - "proxy_agent_platform/core/error_handling.py"
        - "tests/security/test_error_handling.py"

  - step_id: "S4_secrets_management_audit"
    name: "Audit and Secure Secrets Management"
    description: "Review and implement secure secrets management practices"
    agent_role: "architect"
    action_type: "review"
    action_details:
      review_type: "secrets_audit"
      scope: "entire_codebase"
      focus_areas:
        - "hardcoded_secrets"
        - "environment_variable_usage"
        - "api_key_exposure"
        - "database_credentials"
    dependencies:
      - task_id: "S1_security_analysis"
        dependency_type: "requires"
    parallel_group: "security_fixes"
    timeout_minutes: 30
    validation_gates:
      - name: "secrets_security_validation"
        description: "Ensure no secrets are exposed in code"
        agent_role: "quality"
        validation_command: "scan_for_secrets"
        success_criteria:
          hardcoded_secrets: 0
          environment_variables_used: true
          secure_patterns: true
        failure_action: "block"
        retry_count: 1
    tdd_required: false
    input_context:
      scan_patterns:
        - "api_key"
        - "password"
        - "secret"
        - "token"
      exclude_paths:
        - "tests/"
        - "examples/"
    expected_outputs:
      - "secrets_audit_report"
      - "remediation_recommendations"
      - "security_best_practices"
    success_criteria:
      no_secrets_exposed: true
      secure_patterns_identified: true
      recommendations_provided: true

  - step_id: "S5_security_testing"
    name: "Comprehensive Security Testing"
    description: "Execute security test suite to validate all fixes"
    agent_role: "quality"
    action_type: "test"
    action_details:
      test_type: "security_validation"
      test_categories:
        - "cors_security_tests"
        - "error_handling_tests"
        - "secrets_exposure_tests"
        - "input_validation_tests"
      coverage_requirement: 100
    dependencies:
      - task_id: "S2_cors_vulnerability_fix"
        dependency_type: "requires"
      - task_id: "S3_error_handling_hardening"
        dependency_type: "requires"
      - task_id: "S4_secrets_management_audit"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 35
    validation_gates:
      - name: "security_test_validation"
        description: "All security tests must pass"
        agent_role: "quality"
        validation_command: "run_security_test_suite"
        success_criteria:
          all_tests_passed: true
          coverage_threshold_met: true
          vulnerability_scan_clean: true
        failure_action: "block"
        retry_count: 2
    tdd_required: false
    input_context:
      test_suite_path: "tests/security/"
      vulnerability_scanner: "bandit"
      coverage_tools: ["pytest-cov"]
    expected_outputs:
      - "security_test_results"
      - "vulnerability_scan_report"
      - "coverage_report"
    success_criteria:
      security_tests_passed: true
      vulnerability_scan_clean: true
      coverage_above_threshold: true

  - step_id: "S6_integration_security_validation"
    name: "Integration Security Validation"
    description: "Validate security fixes work correctly in integrated system"
    agent_role: "integration"
    action_type: "integrate"
    action_details:
      integration_type: "security_validation"
      test_scenarios:
        - "cors_request_validation"
        - "error_response_sanitization"
        - "end_to_end_security_flow"
      production_simulation: true
    dependencies:
      - task_id: "S5_security_testing"
        dependency_type: "requires"
    parallel_group: null
    timeout_minutes: 40
    validation_gates:
      - name: "integration_security_check"
        description: "Security measures work in integrated environment"
        agent_role: "integration"
        validation_command: "validate_integrated_security"
        success_criteria:
          cors_integration_secure: true
          error_handling_secure: true
          no_information_leakage: true
        failure_action: "block"
        retry_count: 2
    tdd_required: false
    input_context:
      test_environment: "staging"
      security_scenarios: "comprehensive"
      performance_impact: "minimal"
    expected_outputs:
      - "integration_security_report"
      - "performance_impact_analysis"
      - "production_readiness_assessment"
    success_criteria:
      integration_security_validated: true
      performance_acceptable: true
      production_ready: true
    git_integration:
      create_commit: true
      commit_type: "feat"
      commit_message: "security: complete critical security audit workflow\n\nFinal security validation and integration testing complete\n- All CORS vulnerabilities resolved\n- Error handling hardened\n- Secrets management audited\n- Comprehensive security testing passed\n- Production-ready security posture achieved"
      files_to_commit:
        - "docs/security/final_security_report.md"
        - "tests/integration/security_integration_tests.py"
      create_tag: true
      tag_name: "security-audit-v1.0.0"
      tag_message: "Critical security audit completed - production ready"

# Global validation gates
global_validation_gates:
  - name: "overall_security_validation"
    description: "Comprehensive security validation across all fixes"
    agent_role: "quality"
    validation_command: "comprehensive_security_audit"
    success_criteria:
      all_vulnerabilities_fixed: true
      security_tests_passing: true
      no_new_vulnerabilities: true
    failure_action: "block"
    retry_count: 1

# Success criteria
success_criteria:
  cors_vulnerability_resolved: true
  error_handling_secured: true
  secrets_management_audited: true
  security_tests_passing: true
  integration_validated: true
  production_ready: true

# Human interaction
human_checkpoints:
  - "S6_integration_security_validation"
approval_required: false

# Metadata and tracking
created_by: "workflow_system"
tags:
  - "security"
  - "critical"
  - "cors"
  - "vulnerability_fix"
  - "production_blocker"