import { useEffect, useRef, useState } from "react";
import { useInView } from "react-intersection-observer";
import { cn } from "@/lib/utils";
import type { TileBase } from "@/types/tile";
import type { Contact } from "@/lib/types/contact";
import AppIcon from "@/components/app-icon";
import { InteractiveCard } from "@/components/ui/interactive-card";
import { Button } from "@/components/ui/button";
import {
  CalendarClock,
  ListTodo,
  MessagesSquare,
  BellRing,
  Stethoscope,
  GraduationCap,
  Users2,
  Gamepad2,
  Layout,
  Calendar,
  CheckSquare,
  MessageSquare,
  Heart,
  Book,
  Play,
  ExternalLink,
  Clock,
  AlertCircle,
  Users,
  Award,
  Zap,
  Star,
  Trophy,
  Target,
  Sparkles,
  Brain,
  Rocket,
  Globe,
  Music,
  Film,
  Palette,
  Coffee,
  Laptop,
  Smartphone,
  BookOpen,
  Headphones
} from "lucide-react";
import MainFocusCard from "@/components/main-focus-card";
import { formatDistanceToNow } from "date-fns";
import StackedAvatars from "@/components/stacked-avatars";

interface TileAction {
  id: string;
  label: string;
}

export interface TileFeedTile extends TileBase {
  app?: string;
  apps?: string[];
  timestamp: string | Date;
  achievement?: boolean;
  aiSummary?: string;
  aiActionSuggestion?: string;
  details?: Record<string, unknown>;
  actions?: TileAction[];
  trending?: boolean;
  urgency?: number;
  importance?: number;
  size?: string;
  category?: string;
}

interface TileFeedProps {
  tiles: TileFeedTile[];
  contacts: Record<string, Contact>;
}

// Add interface for calendar tile details
interface CalendarTileDetails {
  location?: string;
  duration?: string;
  attendees?: string[];
  agenda?: string[];
  previousMeetingNotes?: string;
  [key: string]: unknown;
}

export default function TileFeed({ tiles, contacts }: TileFeedProps) {
  const [visibleTiles, setVisibleTiles] = useState(tiles.slice(0, 15));
  const { ref, inView } = useInView({
    threshold: 0.1,
    triggerOnce: false,
  });

  // Load more tiles when bottom is reached
  useEffect(() => {
    if (inView) {
      setVisibleTiles((prev) => [
        ...prev,
        ...tiles.slice(prev.length, prev.length + 10),
      ]);
    }
  }, [inView, tiles]);

  // Get icon based on category
  const getCategoryIcon = (category: string) => {
    switch (category?.toLowerCase()) {
      case "calendar":
        return <CalendarClock className="h-5 w-5" />;
      case "tasks":
        return <ListTodo className="h-5 w-5" />;
      case "messengers":
        return <MessagesSquare className="h-5 w-5" />;
      case "alerts":
        return <BellRing className="h-5 w-5" />;
      case "health":
        return <Stethoscope className="h-5 w-5" />;
      case "learn":
        return <GraduationCap className="h-5 w-5" />;
      case "social":
        return <Users2 className="h-5 w-5" />;
      case "entertainment":
        return <Gamepad2 className="h-5 w-5" />;
      case "productivity":
        return <Zap className="h-5 w-5" />;
      case "achievement":
        return <Trophy className="h-5 w-5" />;
      case "trending":
        return <Sparkles className="h-5 w-5" />;
      case "global":
        return <Globe className="h-5 w-5" />;
      case "ai":
        return <Brain className="h-5 w-5" />;
      case "music":
        return <Music className="h-5 w-5" />;
      case "movie":
        return <Film className="h-5 w-5" />;
      case "art":
        return <Palette className="h-5 w-5" />;
      case "break":
        return <Coffee className="h-5 w-5" />;
      case "desktop":
        return <Laptop className="h-5 w-5" />;
      case "mobile":
        return <Smartphone className="h-5 w-5" />;
      case "reading":
        return <BookOpen className="h-5 w-5" />;
      case "audio":
        return <Headphones className="h-5 w-5" />;
      case "favorite":
        return <Star className="h-5 w-5" />;
      default:
        return <Layout className="h-5 w-5" />;
    }
  };

  // Get action buttons based on category
  const getActionButtons = (tile: TileFeedTile) => {
    // Use the actions from the tile if available, which are generated by generateContextualActions
    if (tile.actions && tile.actions.length > 0) {
      return (
        <div className="flex gap-3 mt-4" data-oid="td93-es">
          {/* Primary action - opens the app */}
          {tile.actions[0] && (
            <Button
              className="flex-1 bg-indigo-600 hover:bg-indigo-700"
              data-oid="og.phb4"
            >
              {tile.actions[0].label}
            </Button>
          )}

          {/* Secondary action - AI automation */}
          {tile.actions[1] && (
            <Button
              className="flex-1 bg-purple-600 hover:bg-purple-700"
              data-oid="cjjql8x"
            >
              {tile.actions[1].label}
            </Button>
          )}

          {/* Tertiary action - defer/dismiss */}
          {tile.actions[2] && (
            <Button variant="outline" className="flex-1" data-oid="_f0_csm">
              {tile.actions[2].label}
            </Button>
          )}
        </div>
      );
    }

    // Fallback to the old implementation if no actions are available
    const actionMap: Record<string, { primary: string; secondary: string }> = {
      calendar: { primary: "Join Meeting", secondary: "Reschedule" },
      tasks: { primary: "Complete Task", secondary: "Snooze" },
      messengers: { primary: "Reply", secondary: "Mark Read" },
      alerts: { primary: "View Alert", secondary: "Dismiss" },
      health: { primary: "Track Progress", secondary: "Set Reminder" },
      learn: { primary: "Start Learning", secondary: "Save for Later" },
      social: { primary: "View Content", secondary: "Share" },
      entertainment: { primary: "Play Now", secondary: "Add to List" },
    };

    const defaultAction = { primary: "View Details", secondary: "Dismiss" };
    const action = tile.category ? actionMap[tile.category] || defaultAction : defaultAction;

    return (
      <div className="flex gap-3 mt-4" data-oid="4krtlpx">
        <Button
          className="flex-1 bg-indigo-600 hover:bg-indigo-700"
          data-oid="cha114e"
        >
          {action.primary}
        </Button>
        <Button variant="outline" className="flex-1" data-oid="e:evuz1">
          {action.secondary}
        </Button>
      </div>
    );
  };

  // Modify the getColorForTile function to return proper types
  const getColorForTile = (tile: TileFeedTile): string => {
    // Determine color based on app
    const app = tile.app || (tile.apps && tile.apps.length > 0 ? tile.apps[0] : "default");
    const colorMap: Record<string, string> = {
      calendar: "purple",
      email: "blue",
      whatsapp: "green",
      slack: "teal",
      task: "indigo",
      weather: "cyan",
      notification: "red",
      zoom: "blue",
      fitbit: "cyan",
      jira: "indigo",
      github: "gray",
      coursera: "blue",
      localEvents: "orange",
      social: "pink",
      default: "purple"
    };
    
    return colorMap[app] || "purple";
  };

  // Add this function that takes a tile parameter
  const getHoverIntensity = (tile: TileFeedTile): "light" | "medium" | "heavy" => {
    const priority = (tile.urgency || 1) * (tile.importance || 1);
    if (priority > 15) return "heavy";
    if (priority > 8) return "medium";
    return "light";
  };

  if (!tiles || tiles.length === 0) {
    return null;
  }

  return (
    <div className="w-full">
      <div className="grid grid-cols-1 gap-4">
        {tiles.map((tile) => (
          <InteractiveCard
            key={`feed-${tile.id}`}
            color={getColorForTile(tile)}
            isTrending={tile.trending}
            expandedContent={tile.aiSummary}
            hoverScale={1.03}
            dropShadowIntensity={getHoverIntensity(tile)}
            className={cn("p-0 h-full", {
              "bg-white/85 dark:bg-slate-900/85": true,
              "backdrop-blur-[8px]": true,
              "rounded-xl shadow-sm": true,
              "transition-all duration-200 ease-in-out": true,
              "hover:shadow-md hover:scale-[1.02]": true,
              "border border-slate-200/50 dark:border-slate-700/50": true,
              "col-span-1": tile.size === "1",
              "col-span-2": tile.size === "2",
              "col-span-3": tile.size === "3",
              "row-span-1": tile.size === "1",
              "row-span-2": tile.size === "2",
            })}
          >
            <div className="h-full flex flex-col">
              <div className="p-4">
                <div className="flex items-start gap-3 mb-3">
                  {/* App icon */}
                  {tile.app && (
                    <div className="shrink-0">
                      <div
                        className={cn(
                          "w-10 h-10 rounded-lg flex items-center justify-center",
                          "bg-gradient-to-br from-indigo-500/20 to-purple-500/20",
                          "text-indigo-600 dark:text-indigo-400"
                        )}
                      >
                        <AppIcon app={tile.app} className="w-5 h-5" />
                      </div>
                    </div>
                  )}

                  {/* Title and metadata */}
                  <div className="flex-1 min-w-0">
                    <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100 truncate">
                      {tile.title}
                    </h3>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="text-xs text-slate-600 dark:text-slate-400">
                        {(() => {
                          try {
                            const date = new Date(tile.timestamp);
                            // Check if date is valid
                            if (Number.isNaN(date.getTime())) {
                              return 'Invalid date';
                            }
                            return formatDistanceToNow(date, {
                              addSuffix: true,
                            });
                          } catch (error) {
                            console.error('Error formatting date:', error);
                            return 'Date unavailable';
                          }
                        })()}
                      </span>
                      {tile.category && (
                        <span className="text-xs text-slate-500 dark:text-slate-500">
                          {tile.category}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Achievement badge */}
                  {tile.achievement && (
                    <div className="shrink-0">
                      <div
                        className={cn(
                          "w-8 h-8 rounded-lg flex items-center justify-center",
                          "bg-gradient-to-br from-amber-500/20 to-orange-500/20",
                          "text-amber-600 dark:text-amber-400"
                        )}
                      >
                        <Trophy className="w-4 h-4" />
                      </div>
                    </div>
                  )}
                </div>

                {/* Content */}
                <div className="space-y-3">
                  <p className="text-xs text-slate-600 dark:text-slate-300">
                    {tile.content}
                  </p>

                  {/* Show attendees for calendar events */}
                  {tile.category === "calendar" && 
                    tile.details && 
                    ((details) => {
                      const attendees = (details as CalendarTileDetails).attendees || [];
                      return Array.isArray(attendees) && attendees.length > 0 ? (
                        <div className="mt-2" data-oid="calendar-attendees">
                          <StackedAvatars 
                            contacts={contacts}
                            attendeeIds={attendees}
                            size="sm"
                            limit={3}
                            showNames={true}
                          />
                        </div>
                      ) : null;
                    })(tile.details)
                  }

                  {/* AI Summary */}
                  {tile.aiSummary && (
                    <div className="mt-3 p-3 rounded-lg bg-indigo-50/50 dark:bg-indigo-900/20">
                      <p className="text-xs text-indigo-700 dark:text-indigo-300">
                        {tile.aiSummary}
                      </p>
                    </div>
                  )}

                  {/* AI suggestions if available */}
                  {tile.aiActionSuggestion && (
                    <div
                      className="mt-2 p-1.5 md:mt-3 md:p-3 bg-indigo-50 dark:bg-indigo-900/20 rounded-md border border-indigo-100 dark:border-indigo-800/30"
                    >
                      <p
                        className="text-xs md:text-sm text-indigo-700 dark:text-indigo-300 flex items-center gap-1 md:gap-2"
                      >
                        <Sparkles
                          className="h-3 w-3 md:h-4 md:w-4 text-indigo-500"
                        />{" "}
                        {tile.aiActionSuggestion}
                      </p>
                    </div>
                  )}

                  {/* Actions */}
                  {tile.actions && tile.actions.length > 0 && (
                    <div className="flex flex-wrap gap-2 mt-3">
                      {tile.actions.map((action) => (
                        <button
                          key={action.id}
                          type="button"
                          className={cn(
                            "px-3 py-1.5 text-xs font-medium rounded-lg",
                            "bg-indigo-100 text-indigo-700",
                            "dark:bg-indigo-900/30 dark:text-indigo-300",
                            "hover:bg-indigo-200 dark:hover:bg-indigo-900/40",
                            "transition-colors duration-200"
                          )}
                        >
                          {action.label}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              {/* Show achievement badge if present */}
              {tile.achievement && (
                <div
                  className="mt-auto text-xs font-medium text-indigo-600 dark:text-indigo-400 flex items-center gap-1"
                  data-oid="_hrkn.f"
                >
                  <span data-oid="44qkf-y">🏆</span>
                </div>
              )}
            </div>
          </InteractiveCard>
        ))}
      </div>

      {/* Infinite scroll trigger */}
      <div ref={ref} className="h-10" />
    </div>
  );
}
