"""
Test database models and schemas.

Comprehensive tests for database functionality to increase coverage.
"""

from datetime import datetime

import pytest

# Import models from correct locations
from src.core.task_models import (
    Achievement,
    FocusSession,
    Task,
    TaskPriority,
    TaskStatus,
    User,
    UserAchievement,
)


class TestEnums:
    """Test all enum types."""

    def test_task_status_enum_values(self):
        """Test TaskStatus enum has all expected values."""
        assert TaskStatus.TODO == "todo"
        assert TaskStatus.IN_PROGRESS == "in_progress"
        assert TaskStatus.IN_REVIEW == "in_review"
        assert TaskStatus.BLOCKED == "blocked"
        assert TaskStatus.COMPLETED == "completed"
        assert TaskStatus.CANCELLED == "cancelled"

    def test_task_priority_enum_values(self):
        """Test TaskPriority enum has all expected values."""
        assert TaskPriority.LOW == "low"
        assert TaskPriority.MEDIUM == "medium"
        assert TaskPriority.HIGH == "high"
        assert TaskPriority.CRITICAL == "critical"


class TestPydanticSchemas:
    """Test Pydantic schemas for API requests/responses."""

    # NOTE: Tests for TaskCreate and UserCreate removed as these models
    # have been replaced by TaskCreateRequest and UserRegister in src/api/
    pass


class TestTaskModel:
    """Test Task model functionality."""

    def test_task_model_creation(self):
        """Test Task model can be created with all fields."""
        task = Task(
            title="Test Task",
            description="Test description",
            project_id="project-123",
            status=TaskStatus.TODO,
            priority=TaskPriority.HIGH,
            tags=["important", "urgent"],
        )

        assert task.title == "Test Task"
        assert task.description == "Test description"
        assert task.project_id == "project-123"
        assert task.status == TaskStatus.TODO
        assert task.priority == TaskPriority.HIGH
        assert task.tags == ["important", "urgent"]
        assert task.task_id is not None  # Generated by default

    def test_task_model_defaults(self):
        """Test Task model default values."""
        task = Task(
            title="Minimal Task",
            description="Minimal description",
            project_id="project-456"
        )

        # Test defaults
        assert task.title == "Minimal Task"
        assert task.status == TaskStatus.TODO
        assert task.priority == TaskPriority.MEDIUM
        assert task.tags == []


class TestUserModel:
    """Test User model functionality."""

    def test_user_model_creation(self):
        """Test User model creation with all fields."""
        user = User(
            email="test@example.com",
            username="testuser",
            password_hash="hashedpassword",
            full_name="Test User",
            timezone="America/New_York",
            is_active=True,
        )

        assert user.email == "test@example.com"
        assert user.username == "testuser"
        assert user.password_hash == "hashedpassword"
        assert user.full_name == "Test User"
        assert user.timezone == "America/New_York"
        assert user.is_active is True
        assert user.user_id is not None  # Generated by default

    def test_user_defaults(self):
        """Test user default values."""
        user = User(email="gamer@example.com", username="gamer")

        # Test defaults
        assert user.timezone == "UTC"
        assert user.is_active is True
        assert user.preferences == {}


class TestFocusSessionModel:
    """Test FocusSession model functionality."""

    def test_focus_session_creation(self):
        """Test FocusSession model creation."""
        session = FocusSession(
            user_id="user-123",
            task_id="task-456",
            planned_duration_minutes=90,
            interruptions=2,
            productivity_score=85.5,
        )

        assert session.user_id == "user-123"
        assert session.task_id == "task-456"
        assert session.planned_duration_minutes == 90
        assert session.interruptions == 2
        assert session.productivity_score == 85.5
        assert session.session_id is not None  # Generated by default
        assert session.is_active is True  # Not ended yet


# NOTE: Additional tests removed as they reference models that no longer exist
# or use fields that have been refactored. New tests should be written for current models.


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
