"""baseline migration from existing schema

Revision ID: 33d9c3a5619f
Revises: 
Create Date: 2025-10-25 20:14:44.189035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d9c3a5619f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('habit_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('habit_id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.drop_index(op.f('idx_energy_user_timestamp'), table_name='energy_readings')
    op.drop_table('energy_readings')
    op.drop_index(op.f('idx_metrics_date'), table_name='productivity_metrics')
    op.drop_index(op.f('idx_metrics_period'), table_name='productivity_metrics')
    op.drop_index(op.f('idx_metrics_user'), table_name='productivity_metrics')
    op.drop_table('productivity_metrics')
    op.drop_index(op.f('idx_temporal_current'), table_name='kg_temporal_entities')
    op.drop_index(op.f('idx_temporal_entity_id'), table_name='kg_temporal_entities')
    op.drop_index(op.f('idx_temporal_relevance'), table_name='kg_temporal_entities')
    op.drop_index(op.f('idx_temporal_user_type'), table_name='kg_temporal_entities')
    op.drop_index(op.f('idx_temporal_valid_from'), table_name='kg_temporal_entities')
    op.drop_index(op.f('idx_temporal_valid_to'), table_name='kg_temporal_entities')
    op.drop_table('kg_temporal_entities')
    op.drop_index(op.f('idx_pattern_entity'), table_name='kg_recurring_patterns')
    op.drop_index(op.f('idx_pattern_predicted'), table_name='kg_recurring_patterns')
    op.drop_index(op.f('idx_pattern_user_type'), table_name='kg_recurring_patterns')
    op.drop_table('kg_recurring_patterns')
    op.drop_index(op.f('idx_shopping_category'), table_name='kg_shopping_items')
    op.drop_index(op.f('idx_shopping_recurring'), table_name='kg_shopping_items')
    op.drop_index(op.f('idx_shopping_urgency'), table_name='kg_shopping_items')
    op.drop_index(op.f('idx_shopping_user_status'), table_name='kg_shopping_items')
    op.drop_table('kg_shopping_items')
    op.drop_table('user_progress')
    op.drop_table('task_templates')
    op.drop_index(op.f('idx_kg_relationships_from'), table_name='kg_relationships')
    op.drop_index(op.f('idx_kg_relationships_to'), table_name='kg_relationships')
    op.drop_index(op.f('idx_kg_relationships_type'), table_name='kg_relationships')
    op.drop_table('kg_relationships')
    op.drop_index(op.f('idx_dependencies_depends'), table_name='task_dependencies')
    op.drop_index(op.f('idx_dependencies_task'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('idx_event_entity'), table_name='kg_event_log')
    op.drop_index(op.f('idx_event_pattern'), table_name='kg_event_log')
    op.drop_index(op.f('idx_event_type'), table_name='kg_event_log')
    op.drop_index(op.f('idx_event_user_time'), table_name='kg_event_log')
    op.drop_table('kg_event_log')
    op.drop_index(op.f('idx_created_at'), table_name='messages')
    op.drop_index(op.f('idx_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('idx_temporal_rel_current'), table_name='kg_temporal_relationships')
    op.drop_index(op.f('idx_temporal_rel_from'), table_name='kg_temporal_relationships')
    op.drop_index(op.f('idx_temporal_rel_id'), table_name='kg_temporal_relationships')
    op.drop_index(op.f('idx_temporal_rel_to'), table_name='kg_temporal_relationships')
    op.drop_table('kg_temporal_relationships')
    op.drop_index(op.f('idx_pref_confidence'), table_name='kg_preference_history')
    op.drop_index(op.f('idx_pref_user_key'), table_name='kg_preference_history')
    op.drop_index(op.f('idx_pref_valid_from'), table_name='kg_preference_history')
    op.drop_table('kg_preference_history')
    op.drop_index(op.f('idx_kg_entities_name'), table_name='kg_entities')
    op.drop_index(op.f('idx_kg_entities_type'), table_name='kg_entities')
    op.drop_index(op.f('idx_kg_entities_user_id'), table_name='kg_entities')
    op.drop_table('kg_entities')
    op.add_column('achievements', sa.Column('icon', sa.String(), nullable=True))
    op.alter_column('achievements', 'achievement_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('achievements', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('achievements', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('achievements', 'xp_reward',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('achievements', 'criteria',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('achievements', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_achievements_category'), table_name='achievements')
    op.drop_column('achievements', 'badge_icon')
    op.drop_column('achievements', 'is_active')
    op.drop_column('achievements', 'rarity')
    op.drop_column('achievements', 'category')
    op.alter_column('compass_zones', 'zone_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('compass_zones', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('compass_zones', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('compass_zones', 'icon',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('compass_zones', 'color',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('compass_zones', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('compass_zones', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('compass_zones', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('compass_zones', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_compass_zones_order'), table_name='compass_zones')
    op.drop_index(op.f('idx_compass_zones_user'), table_name='compass_zones')
    op.create_index(op.f('ix_compass_zones_user_id'), 'compass_zones', ['user_id'], unique=False)
    op.alter_column('energy_snapshots', 'snapshot_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('energy_snapshots', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('energy_snapshots', 'recorded_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('energy_snapshots', 'time_of_day',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_energy_snapshots_level'), table_name='energy_snapshots')
    op.drop_index(op.f('idx_energy_snapshots_user'), table_name='energy_snapshots')
    op.create_index(op.f('ix_energy_snapshots_user_id'), 'energy_snapshots', ['user_id'], unique=False)
    op.add_column('focus_sessions', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('focus_sessions', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.alter_column('focus_sessions', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('focus_sessions', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'started_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'ended_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'interruptions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_focus_started'), table_name='focus_sessions')
    op.drop_index(op.f('idx_focus_task'), table_name='focus_sessions')
    op.drop_index(op.f('idx_focus_user'), table_name='focus_sessions')
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    op.drop_constraint(None, 'focus_sessions', type_='foreignkey')
    op.drop_column('focus_sessions', 'productivity_score')
    op.drop_column('focus_sessions', 'metadata')
    op.drop_column('focus_sessions', 'project_id')
    op.drop_column('focus_sessions', 'was_completed')
    op.drop_column('focus_sessions', 'actual_duration_minutes')
    op.drop_column('focus_sessions', 'planned_duration_minutes')
    op.drop_column('focus_sessions', 'session_type')
    op.add_column('micro_steps', sa.Column('emoji', sa.String(), nullable=True))
    op.add_column('micro_steps', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.alter_column('micro_steps', 'step_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('micro_steps', 'parent_task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('micro_steps', 'delegation_mode',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('micro_steps', 'completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('micro_steps', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_micro_steps_leaf_status'), table_name='micro_steps')
    op.drop_index(op.f('idx_micro_steps_level'), table_name='micro_steps')
    op.drop_index(op.f('idx_micro_steps_parent_step'), table_name='micro_steps')
    op.drop_index(op.f('idx_micro_steps_status'), table_name='micro_steps')
    op.drop_index(op.f('idx_micro_steps_step_number'), table_name='micro_steps')
    op.create_index(op.f('ix_micro_steps_parent_task_id'), 'micro_steps', ['parent_task_id'], unique=False)
    op.drop_column('micro_steps', 'status')
    op.drop_column('micro_steps', 'decomposition_state')
    op.drop_column('micro_steps', 'short_label')
    op.drop_column('micro_steps', 'icon')
    op.drop_column('micro_steps', 'level')
    op.drop_column('micro_steps', 'actual_minutes')
    op.drop_column('micro_steps', 'is_leaf')
    op.drop_column('micro_steps', 'parent_step_id')
    op.alter_column('morning_rituals', 'ritual_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('morning_rituals', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('morning_rituals', 'completion_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('morning_rituals', 'focus_task_1_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'focus_task_2_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'focus_task_3_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'completed_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'skipped',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_morning_rituals_user_date'), table_name='morning_rituals')
    op.create_index(op.f('ix_morning_rituals_user_id'), 'morning_rituals', ['user_id'], unique=False)
    op.alter_column('projects', 'project_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'team_members',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('projects', 'end_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('projects', 'settings',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('projects', 'metadata',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_projects_active'), table_name='projects')
    op.drop_index(op.f('idx_projects_owner'), table_name='projects')
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.alter_column('task_comments', 'comment_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('task_comments', 'author_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('task_comments', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('task_comments', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('task_comments', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_comments_author'), table_name='task_comments')
    op.drop_index(op.f('idx_comments_task'), table_name='task_comments')
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('capture_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('custom_emoji', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('decomposition_state', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('children_ids', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('total_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_leaf', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('leaf_type', sa.String(), nullable=True))
    op.alter_column('tasks', 'task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'parent_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'actual_hours',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'tags',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'started_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'metadata',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'scope',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'delegation_mode',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'is_micro_step',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'micro_steps',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'zone_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_tasks_assignee'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_created'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_parent'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_project'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_zone'), table_name='tasks')
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_zone_id'), 'tasks', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'compass_zones', ['zone_id'], ['zone_id'])
    op.add_column('user_achievements', sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_achievements', 'user_achievement_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user_achievements', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_achievements', 'achievement_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_user_achievements_completed'), table_name='user_achievements')
    op.drop_index(op.f('idx_user_achievements_user'), table_name='user_achievements')
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.drop_column('user_achievements', 'progress')
    op.drop_column('user_achievements', 'context')
    op.drop_column('user_achievements', 'is_completed')
    op.drop_column('user_achievements', 'created_at')
    op.drop_column('user_achievements', 'earned_at')
    op.alter_column('users', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_active'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_active'), 'users', ['is_active'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'"),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.String(),
               server_default=sa.text("'UTC'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('user_achievements', sa.Column('earned_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_achievements', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('user_achievements', sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.add_column('user_achievements', sa.Column('context', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
    op.add_column('user_achievements', sa.Column('progress', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('(0.0)'), nullable=True))
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.create_index(op.f('idx_user_achievements_user'), 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_achievements_completed'), 'user_achievements', ['is_completed'], unique=False)
    op.alter_column('user_achievements', 'achievement_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_achievements', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_achievements', 'user_achievement_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('user_achievements', 'unlocked_at')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_zone_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.create_index(op.f('idx_tasks_zone'), 'tasks', ['zone_id'], unique=False)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_project'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('idx_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('idx_tasks_parent'), 'tasks', ['parent_id'], unique=False)
    op.create_index(op.f('idx_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('idx_tasks_created'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('idx_tasks_assignee'), 'tasks', ['assignee_id'], unique=False)
    op.alter_column('tasks', 'zone_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'micro_steps',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=True)
    op.alter_column('tasks', 'is_micro_step',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('tasks', 'delegation_mode',
               existing_type=sa.String(),
               server_default=sa.text("'do'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'scope',
               existing_type=sa.String(),
               server_default=sa.text("'simple'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'metadata',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'"),
               existing_nullable=True)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'assignee_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'tags',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=True)
    op.alter_column('tasks', 'actual_hours',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               server_default=sa.text('(0.0)'),
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(),
               server_default=sa.text("'medium'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               server_default=sa.text("'todo'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'parent_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'task_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('tasks', 'leaf_type')
    op.drop_column('tasks', 'is_leaf')
    op.drop_column('tasks', 'total_minutes')
    op.drop_column('tasks', 'children_ids')
    op.drop_column('tasks', 'decomposition_state')
    op.drop_column('tasks', 'custom_emoji')
    op.drop_column('tasks', 'level')
    op.drop_column('tasks', 'capture_type')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.create_index(op.f('idx_comments_task'), 'task_comments', ['task_id'], unique=False)
    op.create_index(op.f('idx_comments_author'), 'task_comments', ['author_id'], unique=False)
    op.alter_column('task_comments', 'is_edited',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('task_comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('task_comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('task_comments', 'author_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('task_comments', 'comment_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.create_index(op.f('idx_projects_owner'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('idx_projects_active'), 'projects', ['is_active'], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('projects', 'metadata',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'"),
               existing_nullable=True)
    op.alter_column('projects', 'settings',
               existing_type=sa.TEXT(),
               server_default=sa.text("'{}'"),
               existing_nullable=True)
    op.alter_column('projects', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('projects', 'team_members',
               existing_type=sa.TEXT(),
               server_default=sa.text("'[]'"),
               existing_nullable=True)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('projects', 'project_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_morning_rituals_user_id'), table_name='morning_rituals')
    op.create_index(op.f('idx_morning_rituals_user_date'), 'morning_rituals', ['user_id', 'completion_date'], unique=False)
    op.alter_column('morning_rituals', 'skipped',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(FALSE)'),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'focus_task_3_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'focus_task_2_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'focus_task_1_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('morning_rituals', 'completion_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('morning_rituals', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('morning_rituals', 'ritual_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('micro_steps', sa.Column('parent_step_id', sa.TEXT(), nullable=True))
    op.add_column('micro_steps', sa.Column('is_leaf', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
    op.add_column('micro_steps', sa.Column('actual_minutes', sa.INTEGER(), nullable=True))
    op.add_column('micro_steps', sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('micro_steps', sa.Column('icon', sa.TEXT(), nullable=True))
    op.add_column('micro_steps', sa.Column('short_label', sa.TEXT(), nullable=True))
    op.add_column('micro_steps', sa.Column('decomposition_state', sa.TEXT(), server_default=sa.text("'atomic'"), nullable=True))
    op.add_column('micro_steps', sa.Column('status', sa.TEXT(), server_default=sa.text("'todo'"), nullable=True))
    op.drop_index(op.f('ix_micro_steps_parent_task_id'), table_name='micro_steps')
    op.create_index(op.f('idx_micro_steps_step_number'), 'micro_steps', ['parent_task_id', 'step_number'], unique=False)
    op.create_index(op.f('idx_micro_steps_status'), 'micro_steps', ['status'], unique=False)
    op.create_index(op.f('idx_micro_steps_parent_step'), 'micro_steps', ['parent_step_id'], unique=False)
    op.create_index(op.f('idx_micro_steps_level'), 'micro_steps', ['level'], unique=False)
    op.create_index(op.f('idx_micro_steps_leaf_status'), 'micro_steps', ['is_leaf', 'decomposition_state'], unique=False)
    op.alter_column('micro_steps', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('micro_steps', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('micro_steps', 'delegation_mode',
               existing_type=sa.String(),
               server_default=sa.text("'do'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('micro_steps', 'parent_task_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('micro_steps', 'step_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('micro_steps', 'is_completed')
    op.drop_column('micro_steps', 'emoji')
    op.add_column('focus_sessions', sa.Column('session_type', sa.TEXT(), server_default=sa.text("'focus'"), nullable=True))
    op.add_column('focus_sessions', sa.Column('planned_duration_minutes', sa.INTEGER(), nullable=False))
    op.add_column('focus_sessions', sa.Column('actual_duration_minutes', sa.INTEGER(), nullable=True))
    op.add_column('focus_sessions', sa.Column('was_completed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.add_column('focus_sessions', sa.Column('project_id', sa.TEXT(), nullable=True))
    op.add_column('focus_sessions', sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
    op.add_column('focus_sessions', sa.Column('productivity_score', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.create_foreign_key(None, 'focus_sessions', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    op.create_index(op.f('idx_focus_user'), 'focus_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_focus_task'), 'focus_sessions', ['task_id'], unique=False)
    op.create_index(op.f('idx_focus_started'), 'focus_sessions', ['started_at'], unique=False)
    op.alter_column('focus_sessions', 'interruptions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'task_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('focus_sessions', 'is_completed')
    op.drop_column('focus_sessions', 'duration_minutes')
    op.drop_index(op.f('ix_energy_snapshots_user_id'), table_name='energy_snapshots')
    op.create_index(op.f('idx_energy_snapshots_user'), 'energy_snapshots', ['user_id', 'recorded_at'], unique=False)
    op.create_index(op.f('idx_energy_snapshots_level'), 'energy_snapshots', ['user_id', 'energy_level'], unique=False)
    op.alter_column('energy_snapshots', 'time_of_day',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('energy_snapshots', 'recorded_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('energy_snapshots', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('energy_snapshots', 'snapshot_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_compass_zones_user_id'), table_name='compass_zones')
    op.create_index(op.f('idx_compass_zones_user'), 'compass_zones', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_compass_zones_order'), 'compass_zones', ['user_id', 'sort_order'], unique=False)
    op.alter_column('compass_zones', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('compass_zones', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('compass_zones', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(TRUE)'),
               existing_nullable=True)
    op.alter_column('compass_zones', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('compass_zones', 'color',
               existing_type=sa.String(),
               server_default=sa.text("'#3b82f6'"),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('compass_zones', 'icon',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('compass_zones', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('compass_zones', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('compass_zones', 'zone_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('achievements', sa.Column('category', sa.TEXT(), nullable=False))
    op.add_column('achievements', sa.Column('rarity', sa.TEXT(), server_default=sa.text("'common'"), nullable=True))
    op.add_column('achievements', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
    op.add_column('achievements', sa.Column('badge_icon', sa.TEXT(), nullable=True))
    op.create_index(op.f('idx_achievements_category'), 'achievements', ['category'], unique=False)
    op.alter_column('achievements', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('achievements', 'criteria',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('achievements', 'xp_reward',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('achievements', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('achievements', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('achievements', 'achievement_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('achievements', 'icon')
    op.create_table('kg_entities',
    sa.Column('entity_id', sa.TEXT(), nullable=True),
    sa.Column('entity_type', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("entity_type IN ('person', 'device', 'location', 'project')"),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'name')
    )
    op.create_index(op.f('idx_kg_entities_user_id'), 'kg_entities', ['user_id'], unique=False)
    op.create_index(op.f('idx_kg_entities_type'), 'kg_entities', ['entity_type'], unique=False)
    op.create_index(op.f('idx_kg_entities_name'), 'kg_entities', ['name'], unique=False)
    op.create_table('kg_preference_history',
    sa.Column('history_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('preference_key', sa.TEXT(), nullable=False),
    sa.Column('preference_value', sa.TEXT(), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('valid_to', sa.TIMESTAMP(), server_default=sa.text("'9999-12-31 23:59:59'"), nullable=True),
    sa.Column('confidence', sa.REAL(), server_default=sa.text('(0.5)'), nullable=True),
    sa.Column('observation_count', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('last_observed', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('idx_pref_valid_from'), 'kg_preference_history', ['valid_from'], unique=False)
    op.create_index(op.f('idx_pref_user_key'), 'kg_preference_history', ['user_id', 'preference_key', 'is_current'], unique=False)
    op.create_index(op.f('idx_pref_confidence'), 'kg_preference_history', ['user_id', 'confidence'], unique=False)
    op.create_table('kg_temporal_relationships',
    sa.Column('version_id', sa.TEXT(), nullable=True),
    sa.Column('relationship_id', sa.TEXT(), nullable=False),
    sa.Column('from_entity_id', sa.TEXT(), nullable=False),
    sa.Column('to_entity_id', sa.TEXT(), nullable=False),
    sa.Column('relationship_type', sa.TEXT(), nullable=False),
    sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('valid_to', sa.TIMESTAMP(), server_default=sa.text("'9999-12-31 23:59:59'"), nullable=True),
    sa.Column('stored_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('stored_to', sa.TIMESTAMP(), server_default=sa.text("'9999-12-31 23:59:59'"), nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('superseded_by', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by'], ['kg_temporal_relationships.version_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('idx_temporal_rel_to'), 'kg_temporal_relationships', ['to_entity_id', 'valid_to'], unique=False)
    op.create_index(op.f('idx_temporal_rel_id'), 'kg_temporal_relationships', ['relationship_id'], unique=False)
    op.create_index(op.f('idx_temporal_rel_from'), 'kg_temporal_relationships', ['from_entity_id', 'valid_to'], unique=False)
    op.create_index(op.f('idx_temporal_rel_current'), 'kg_temporal_relationships', ['relationship_id', 'is_current'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('session_id', sa.TEXT(), nullable=False),
    sa.Column('message_type', sa.TEXT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('agent_type', sa.TEXT(), nullable=False),
    sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('kg_event_log',
    sa.Column('event_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('event_type', sa.TEXT(), nullable=False),
    sa.Column('entity_id', sa.TEXT(), nullable=True),
    sa.Column('event_time', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), nullable=True),
    sa.Column('hour_of_day', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('energy_level', sa.TEXT(), nullable=True),
    sa.Column('recurring_pattern_id', sa.TEXT(), nullable=True),
    sa.CheckConstraint("energy_level IN ('high', 'medium', 'low') OR energy_level IS NULL"),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6'),
    sa.CheckConstraint('hour_of_day >= 0 AND hour_of_day <= 23'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('idx_event_user_time'), 'kg_event_log', ['user_id', 'event_time'], unique=False)
    op.create_index(op.f('idx_event_type'), 'kg_event_log', ['event_type', 'user_id'], unique=False)
    op.create_index(op.f('idx_event_pattern'), 'kg_event_log', ['user_id', 'event_type', 'day_of_week', 'hour_of_day'], unique=False)
    op.create_index(op.f('idx_event_entity'), 'kg_event_log', ['entity_id', 'event_time'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('dependency_id', sa.TEXT(), nullable=True),
    sa.Column('task_id', sa.TEXT(), nullable=False),
    sa.Column('depends_on_task_id', sa.TEXT(), nullable=False),
    sa.Column('dependency_type', sa.TEXT(), server_default=sa.text("'depends_on'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('dependency_id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id')
    )
    op.create_index(op.f('idx_dependencies_task'), 'task_dependencies', ['task_id'], unique=False)
    op.create_index(op.f('idx_dependencies_depends'), 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_table('kg_relationships',
    sa.Column('relationship_id', sa.TEXT(), nullable=True),
    sa.Column('from_entity_id', sa.TEXT(), nullable=False),
    sa.Column('to_entity_id', sa.TEXT(), nullable=False),
    sa.Column('relationship_type', sa.TEXT(), nullable=False),
    sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['from_entity_id'], ['kg_entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['kg_entities.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id'),
    sa.UniqueConstraint('from_entity_id', 'to_entity_id', 'relationship_type')
    )
    op.create_index(op.f('idx_kg_relationships_type'), 'kg_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('idx_kg_relationships_to'), 'kg_relationships', ['to_entity_id'], unique=False)
    op.create_index(op.f('idx_kg_relationships_from'), 'kg_relationships', ['from_entity_id'], unique=False)
    op.create_table('task_templates',
    sa.Column('template_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('title_template', sa.TEXT(), nullable=False),
    sa.Column('description_template', sa.TEXT(), nullable=False),
    sa.Column('default_priority', sa.TEXT(), server_default=sa.text("'medium'"), nullable=True),
    sa.Column('default_estimated_hours', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('default_tags', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('user_progress',
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('total_xp', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('current_level', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('current_streak', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('longest_streak', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_completion_date', sa.DATE(), nullable=True),
    sa.Column('total_tasks_completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('kg_shopping_items',
    sa.Column('item_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('item_name', sa.TEXT(), nullable=False),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expired_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('recurrence_pattern', sa.TEXT(), nullable=True),
    sa.Column('last_purchased', sa.TIMESTAMP(), nullable=True),
    sa.Column('purchase_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('preferred_store', sa.TEXT(), nullable=True),
    sa.Column('urgency', sa.TEXT(), server_default=sa.text("'normal'"), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.CheckConstraint("status IN ('active', 'completed', 'expired', 'cancelled')"),
    sa.CheckConstraint("urgency IN ('urgent', 'normal', 'someday')"),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('idx_shopping_user_status'), 'kg_shopping_items', ['user_id', 'status', 'added_at'], unique=False)
    op.create_index(op.f('idx_shopping_urgency'), 'kg_shopping_items', ['user_id', 'urgency', 'status'], unique=False)
    op.create_index(op.f('idx_shopping_recurring'), 'kg_shopping_items', ['user_id', 'is_recurring'], unique=False)
    op.create_index(op.f('idx_shopping_category'), 'kg_shopping_items', ['user_id', 'category'], unique=False)
    op.create_table('kg_recurring_patterns',
    sa.Column('pattern_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('pattern_type', sa.TEXT(), nullable=False),
    sa.Column('entity_id', sa.TEXT(), nullable=True),
    sa.Column('entity_type', sa.TEXT(), nullable=True),
    sa.Column('recurrence', sa.TEXT(), nullable=False),
    sa.Column('confidence', sa.REAL(), server_default=sa.text('(0.5)'), nullable=True),
    sa.Column('observation_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), nullable=True),
    sa.Column('hour_of_day', sa.INTEGER(), nullable=True),
    sa.Column('first_observed', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_observed', sa.TIMESTAMP(), nullable=False),
    sa.Column('next_predicted', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1'),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6 OR day_of_week IS NULL'),
    sa.CheckConstraint('hour_of_day >= 0 AND hour_of_day <= 23 OR hour_of_day IS NULL'),
    sa.PrimaryKeyConstraint('pattern_id')
    )
    op.create_index(op.f('idx_pattern_user_type'), 'kg_recurring_patterns', ['user_id', 'pattern_type', 'is_active'], unique=False)
    op.create_index(op.f('idx_pattern_predicted'), 'kg_recurring_patterns', ['user_id', 'next_predicted'], unique=False)
    op.create_index(op.f('idx_pattern_entity'), 'kg_recurring_patterns', ['entity_id'], unique=False)
    op.create_table('kg_temporal_entities',
    sa.Column('version_id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.TEXT(), nullable=False),
    sa.Column('entity_type', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('valid_to', sa.TIMESTAMP(), server_default=sa.text("'9999-12-31 23:59:59'"), nullable=True),
    sa.Column('stored_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('stored_to', sa.TIMESTAMP(), server_default=sa.text("'9999-12-31 23:59:59'"), nullable=True),
    sa.Column('relevance_score', sa.REAL(), server_default=sa.text('(1.0)'), nullable=True),
    sa.Column('last_accessed', sa.TIMESTAMP(), nullable=True),
    sa.Column('access_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('superseded_by', sa.TEXT(), nullable=True),
    sa.CheckConstraint("entity_type IN ('person', 'device', 'location', 'project', 'preference', 'shopping_list')"),
    sa.ForeignKeyConstraint(['superseded_by'], ['kg_temporal_entities.version_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('idx_temporal_valid_to'), 'kg_temporal_entities', ['valid_to'], unique=False)
    op.create_index(op.f('idx_temporal_valid_from'), 'kg_temporal_entities', ['valid_from'], unique=False)
    op.create_index(op.f('idx_temporal_user_type'), 'kg_temporal_entities', ['user_id', 'entity_type', 'valid_to'], unique=False)
    op.create_index(op.f('idx_temporal_relevance'), 'kg_temporal_entities', ['user_id', 'relevance_score'], unique=False)
    op.create_index(op.f('idx_temporal_entity_id'), 'kg_temporal_entities', ['entity_id'], unique=False)
    op.create_index(op.f('idx_temporal_current'), 'kg_temporal_entities', ['entity_id', 'is_current'], unique=False)
    op.create_table('productivity_metrics',
    sa.Column('metrics_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('period_type', sa.TEXT(), server_default=sa.text("'daily'"), nullable=True),
    sa.Column('tasks_created', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('tasks_completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('tasks_overdue', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_focus_time', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('planned_focus_time', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('break_time', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('focus_sessions_completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('focus_sessions_started', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('average_productivity_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('xp_earned', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('achievements_unlocked', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('streak_days', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('completion_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('focus_efficiency', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('metrics_id'),
    sa.UniqueConstraint('user_id', 'date', 'period_type')
    )
    op.create_index(op.f('idx_metrics_user'), 'productivity_metrics', ['user_id'], unique=False)
    op.create_index(op.f('idx_metrics_period'), 'productivity_metrics', ['period_type'], unique=False)
    op.create_index(op.f('idx_metrics_date'), 'productivity_metrics', ['date'], unique=False)
    op.create_table('energy_readings',
    sa.Column('reading_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.TEXT(), nullable=False),
    sa.Column('energy_level', sa.REAL(), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=True),
    sa.Column('factors', sa.TEXT(), nullable=True),
    sa.Column('confidence', sa.REAL(), server_default=sa.text('(0.8)'), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index(op.f('idx_energy_user_timestamp'), 'energy_readings', ['user_id', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
